version: "3.9"

services:
  ####################################
  # mysql database
  ####################################
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cyberguards_db_cases_test
    ports:
      - 3307:3306

  ##################################
  # Integration Testing with Case Service
  ##################################
  case_service:
    build:
      context: ../
      dockerfile: ci/Dockerfile.test
    environment:
      #   CASE_SERVICE_PORT: 10000
      - DATABASE_URL=mysql://root:root@host.docker.internal:3307/cyberguards_db_cases_test?schema=public
    depends_on:
      - mysql
    # env_file:
    #   - "../.env"
