# Set the version of docker compose to use
version: "3.9"

services:
  ####################################
  # mysql database
  ####################################
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cyberguards_db_cases_test

  ##################################
  # Integration Testing with Case Service
  ##################################
  case_service:
    build:
      context: ../
      dockerfile: ci/Dockerfile.test
    depends_on:
      - mysql
    environment:
      CASE_SERVICE_PORT: 10000
      CASE_DATABASE_URL: "mysql://root:root@mysql:3306/cyberguards_db_cases_test?schema=public"
    env_file:
      - "../.env"
