FROM node:20
WORKDIR /usr/src/app
COPY package.json .
COPY prisma ./prisma/
COPY ci/wait-for-it.sh ./
RUN chmod +x wait-for-it.sh
RUN npm install
COPY . .
CMD ./wait-for-it.sh -t 40 mysql:3306 -- npm run test